### PR TITLE
Add support for django 4.2

### PR DESCRIPTION
**Pull request by irtazaakram**
Hi,

This PR

- adds support for Django 3.2 & 4.2
- drops support for Django 1.11, 2.0 & 3.0
- drops support for Python 2.7 & 3.6

Thanks,

### CODE REVIEW

**Comment by awais786** [comment]
@pomegranited please review this PR.

**Comment by awais786** [comment]
@bradenmacdonald can you please review this PR or ask some one from your team to make new one ?
it is blocking us on `django42`.

**Comment by bradenmacdonald** [comment]
Hey @symbolist, is this plugin still used/needed on edx.org?

**Comment by symbolist** [comment]
@bradenmacdonald Nope. We are using our in process runtime now. Where exactly is this being referenced from? 

I think all LabXchange specific code should have been removed in:
https://github.com/openedx/edx-platform/pull/31315
https://github.com/edx/edx-internal/pull/7420 (I do not have access to this)

**Comment by bradenmacdonald** [comment]
Thanks @symbolist. As I thought, just wanted to confirm.

@awais786 I'm going to archive this repo - it shouldn't be used. If it's still installed on edx.org, please uninstall it and remove any associated database tables. Or do you need me to publish a "drop tables" migration first?

**Comment by awais786** [comment]
@bradenmacdonald Its coming from configuration [repo](https://github.com/openedx/configuration/blob/0ede094714c0f35adf4a84cec71fc3831aa1f46d/playbooks/roles/edxapp/defaults/main.yml#L587).

`git+https://github.com/open-craft/lx-pathway-plugin.git@ba1d470217cd5908cbd8b56075628bd4eacf7b39#egg=lx-pathway-plugin`

I'll talk to Jeremy and then inform you. Thanks

**Comment by symbolist** [comment]
@awais786 Thanks! The package above it can also be removed:

```
git+https://github.com/open-craft/labxchange-xblocks.git@a0a8a8dad13199014d4bb29cee416289880bde0b#egg=labxchange-xblocks
```

**Comment by connorhaugh** [comment]
@bradenmacdonald and @symbolist 

Looking at our mysql usage, it seems like we still have the lx_pathway table with data in it on prod. Making a quick drop tables migration would be great TYSM. After that is merged we can move to remove the plugin from configuration

Evidence of data in table:

> mysql> SELECT COUNT(*) from lx_pathway_plugin_pathway;
+----------+
| COUNT(*) |
+----------+
|     6234 |
+----------+

Hooray for getting rid of unused things!

**Comment by awais786** [comment]
> Thanks @symbolist. As I thought, just wanted to confirm.
> 
> @awais786 I'm going to archive this repo - it shouldn't be used. If it's still installed on edx.org, please uninstall it and remove any associated database tables. Or do you need me to publish a "drop tables" migration first?

@bradenmacdonald kindly make a pr for `drop tables.`

**Comment by symbolist** [comment]
@connorhaugh Sure.

@awais786 The LabXchange team will take care of this. Will get back.

**Comment by symbolist** [comment]
We have assigned this internally. Should be ready next week.

**Comment by awais786** [comment]
Thanks @symbolist

**Comment by pkulkark** [comment]
@symbolist Sorry we missed that you mentioned someone from LabXchange team will take care of this. If they haven't yet done so, I have a PR for this: https://github.com/labxchange/lx-pathway-plugin/pull/17. CC @bradenmacdonald @awais786

**Comment by symbolist** [comment]
@pkulkark We were going to get to it this week so looks like you beat us to it. Thanks! 🙂

**Comment by bradenmacdonald** [comment]
@symbolist or @awais786 would one of you[r teams] mind reviewing the PR?

**Comment by awais786** [comment]
@pkulkark PR seems fine.

**Pull request closed without merging**
