### PR TITLE
feat: deleting tables. This package has no usage.

### PR DESCRIPTION
**Pull request by awais786**
`python manage.py lms migrate`
```
Running migrations:
  Applying lx_pathway_plugin.0002_delete_pathway... OK
```

`python manage.py cms migrate` both commands should work without any error.

**RAW SQL**
```
--
-- Delete model Pathway
--
DROP TABLE `lx_pathway_plugin_pathway` CASCADE;
```

### CODE REVIEW

**Review by symbolist — APPROVED** [review]
I haven't tested this (don't have the stack set up any more) but the changes look straightforward. 👍🏽

**Comment by symbolist** [comment]
@pkulkark I think you will have to merge this in? Looks like my access has been removed now. 🙂

**Comment by awais786** [comment]
@bradenmacdonald Please merge this.

**Comment by pkulkark** [comment]
@awais786 @symbolist These changes are the same as the one in https://github.com/labxchange/lx-pathway-plugin/pull/17 i.e. it doesn't solve the problem reported. It will still result in the same error. 
I created a new PR: https://github.com/open-craft/lx-pathway-plugin/pull/4, which contains the fix (in a separate commit), along with the previous changes. CC @bradenmacdonald

**Comment by pkulkark** [comment]
Closing this in preference to https://github.com/open-craft/lx-pathway-plugin/pull/4

**Pull request closed without merging**
